#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script para comparar responsáveis do CSV com relatório Infinite Pay
Identifica quais responsáveis do CSV não estão no relatório
"""

import csv
import re

def extrair_nomes_infinitepay(texto):
    """Extrai nomes do relatório Infinite Pay"""
    nomes = set()
    
    # Padrão para encontrar nomes no relatório
    # Formato: NOME VIA AUTOMAÇAO + VALOR
    padrao = r'([A-ZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸ][A-ZÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞŸ\s]+?)\s+VIA AUTOMAÇAO'
    
    matches = re.findall(padrao, texto)
    for match in matches:
        nome = match.strip()
        if nome and len(nome) > 3:  # Nome deve ter pelo menos 3 caracteres
            nomes.add(nome)
    
    return nomes

def normalizar_nome(nome):
    """Normaliza nome para comparação"""
    # Converter para maiúsculas e remover espaços extras
    return ' '.join(nome.upper().split())

def main():
    print("🔍 COMPARANDO CSV vs RELATÓRIO INFINITE PAY")
    print("=" * 60)
    
    # Arquivo CSV
    csv_file = "responsaveis_com_dividas_20250824_131824.csv"
    
    # Relatório Infinite Pay (31 de agosto)
    relatorio_infinitepay = """
VANESSA GOSSON GADELHA DE FREITAS FORTES + 78,00
ALINE MANETTI LOPES BARANSKI VIA AUTOMAÇAO + 6,00
GIULLIANE ROCHA BOTARELI DANTAS VIA AUTOMAÇAO + 6,00
SUELY ALESSANDRA DA SILVA ALVES VIA AUTOMAÇAO + 6,00
CLEBER PEDRO DE OLIVEIRA VIA AUTOMAÇAO + 6,00
LUCAS RAMATIS VIA AUTOMAÇAO + 6,00
SOUSA BERENICE DE CARVALHO VIA AUTOMAÇAO + 14,00
VERANA SIMÃO DE HOLANDA MOURA VIA AUTOMAÇAO + 6,00
ANA LUIZA DOS SANTOS CRUZ VIA AUTOMAÇAO + 9,00
ROSINARA DA SILVA BORGES SANTANA VIA AUTOMAÇAO + 9,00
JESSICA KAROLINE CAMPOS COSTA VIA AUTOMAÇAO + 18,00
JAZIA AMARILES DA SILVA OLIVEIRA VIA AUTOMAÇAO + 16,00
ASENATE DAMARIS CAETANO DA ROCHA VIA AUTOMAÇAO + 8,00
CHRISTIELLE DE LIMA CONRADO VIA AUTOMAÇAO + 6,00
MARIA DE FATIMA DA SILVA FARIAS SOARES VIA AUTOMAÇAO + 6,00
MARCIA TALITA VIA AUTOMAÇAO + 10,00
HAGAR MARIA DE ANDRADE PINHEIRO VIA AUTOMAÇAO + 19,00
MARCOS SANT'ANNA DA SILVA JUNIOR VIA AUTOMAÇAO + 10,00
MARIA MARILENE DE OLIVEIRA VIA AUTOMAÇAO + 32,00
MARIANGELA MOTA DE OLIVEIRA NUNES VIA AUTOMAÇAO + 6,00
MARILIA DE MOURA CAFÉ FREIRE VIA AUTOMAÇAO + 8,00
LUCIANA MONTEIRO MARQUES VIA AUTOMAÇAO + 74,00
ANA CLEIDE DE AGUIAR FERREIRA VIA AUTOMAÇAO + 11,00
CASSIA CASTILHO MAROTTI VIA AUTOMAÇAO + 64,00
CARLA PAVONE SANTISTEBAN VIA AUTOMAÇAO + 72,00
MARCOS AURELIO PEREIRA DE AZEVEDO VIA AUTOMAÇAO + 42,00
FLAVIA DE OLIVEIRA GOMES DE ARAÚJO VIA AUTOMAÇAO + 5,00
MARIA DE FÁTIMA DA SILVA LIMA VIA AUTOMAÇAO + 10,00
JANAÍNA CORDULA DO LAGO VIA AUTOMAÇAO + 12,00
ELIANDERSON OLIVEIRA DOS SANTOS VIA AUTOMAÇAO + 8,00
CARLA SONEIDE DA SILVA OLIVEIRA BATISTA VIA AUTOMAÇAO + 24,00
JANAINA ATALIBA DE MELO SOUZA VIA AUTOMAÇAO + 23,00
ALEXANDRA LIMA BEZERRA VIA AUTOMAÇAO + 21,00
ADRIANA SANTOS LEÔNCIO BRANDÃO VIA AUTOMAÇAO + 11,00
JAMILE MARQUES BARROS DA SILVA VIA AUTOMAÇAO + 5,00
PAULA LILIANE MEDEIROS DA CONCEIÇÃO VIA AUTOMAÇAO + 50,00
MARIA JOSENY VIA AUTOMAÇAO + 11,00
ADRIANO ELISMAEL MACÊDO DE PAIVA VIA AUTOMAÇAO + 38,00
MARIANA SILVA VIA AUTOMAÇAO + 47,00
MARCOS DELGADO DA SILVA VIA AUTOMAÇAO + 28,00
ELIZANDRO HEBERT RENOVATO DE MIRANDA VIA AUTOMAÇAO + 23,00
DIUANA NUNES DA SILVA VIA AUTOMAÇAO + 44,00
AURICEA MARIA DE MEDEIROS VIA AUTOMAÇAO + 11,00
IRANIR RIBEIRO DA SILVA BATISTA VIA AUTOMAÇAO + 56,00
ELIANE DA SILVA RODRIGUES VIA AUTOMAÇAO + 6,00
ERIKACIA DA SILVA BATISTA DOURADO VIA AUTOMAÇAO + 6,00
ALDENISE RAMOS CARNEIRO DA CUNHA VIA AUTOMAÇAO + 14,00
ROBERTA MONTEIRO DE SOUZA VIEIRA VIA AUTOMAÇAO + 10,00
KATIA ALVES MALHEIROS VIA AUTOMAÇAO + 12,00
MARIA KALINA MAIA DE OLIVEIRA VIA AUTOMAÇAO + 10,00
PATRICIA LOPES DA SILVA VIA AUTOMAÇAO + 19,00
SAMARA LOPES DE QUEIROZ VIA AUTOMAÇAO + 20,00
JOAO FRANCISCO DE SOUZA NETO VIA AUTOMAÇAO + 25,00
LISANDRA ALMEIDA DE OLIVEIRA VIA AUTOMAÇAO + 6,00
KARLA DANIELLA VIEIRA E SILVA ARAUJO VIA AUTOMAÇAO + 10,00
RAIZA CRISTINA PRAXEDES DA SILVA VIA AUTOMAÇAO + 6,00
MARTA DE HOLLANDA FRANCO ALBUQUERQUE VIA AUTOMAÇAO + 12,00
YARA ANGELICA ALVES FERNANDES VIA AUTOMAÇAO + 6,00
RAYANE PONTES VIA AUTOMAÇAO + 20,00
MIRIÃ KELLY CHAGAS DO NASCIMENTO OLIVEIRA VIA AUTOMAÇAO + 6,00
JAQUELINE GOMES GOMES DA SILVA VIA AUTOMAÇAO + 27,00
FABIANA FREIRE RODRIGUES DE MEDEIROS VIA AUTOMAÇAO + 6,00
ARQUIMEDES JOSE EPIFANIO DA SILVA VIA AUTOMAÇAO + 13,00
GENIFFER LIMA DE BRITO MELO VIA AUTOMAÇAO + 41,00
HELENA LEITE DA SILVA ALENCAR VIA AUTOMAÇAO + 28,00
FERNANDA CRISTINA DA SILVA MEDEIROS VIA AUTOMAÇAO + 41,00
MARCOS SANT'ANNA DA SILVA JUNIOR VIA AUTOMAÇAO + 10,00
MARIANA LIMA DE PAIVA PERRUCI VIA AUTOMAÇAO + 6,00
PATRICIA DA SILVA ROCHA VIA AUTOMAÇAO + 27,00
PONCIO PABLO BERTOLDO DA COSTA VIA AUTOMAÇAO + 10,00
GUSTAVO RAPOSO VIA AUTOMAÇAO + 12,00
FLAVIANA BEZERRA LEAO FONSECA VIA AUTOMAÇAO + 41,00
SUERDA MEDEIROS DE SOUZA SANTOS VIA AUTOMAÇAO + 73,00
KRISTIANE GLACIENE NUNES FILGUEIRA CAMARA VIA AUTOMAÇAO + 29,00
PAULO CESAR DE LIMA VIA AUTOMAÇAO + 43,00
TASSIA CAMILA DA SILVA VIA AUTOMAÇAO + 16,00
CRISTIANNE MARCELLE MEDEIROS DOS SANTOS MELO VIA AUTOMAÇAO + 11,00
ROBEILTON AZEVEDO DA SILVA GOMES VIA AUTOMAÇAO + 30,00
JUCIARA MARIA SILVA DO NASCIMENTO VIA AUTOMAÇAO + 26,00
MICARLA GOMES DE PONTES VIA AUTOMAÇAO + 38,00
JULLIETE GONÇALVES DE OLIVEIRA PIMENTA VIA AUTOMAÇAO + 15,00
CLAUDIANA MARIA DE OLIVEIRA MARTINS VIA AUTOMAÇAO + 20,00
KEYLANE MARQUES DA SILVA RAMOS VIA AUTOMAÇAO + 8,00
ANDREZA CARVALHO DE LIMA TELLES VIA AUTOMAÇAO + 6,00
VANIA CLEIDE DE MORAIS SILVA LIRA VIA AUTOMAÇAO + 62,00
MONICA PATRICIA LINHARES VIA AUTOMAÇAO + 20,00
DAYANNY DUARTE DE MOURA FERREIRA VIA AUTOMAÇAO + 24,00
SUZETE LOPES GALVÃO VIA AUTOMAÇAO + 12,00
PATRICIA TORRES VIA AUTOMAÇAO + 40,00
AMANDA AMANDA VIA AUTOMAÇAO + 10,00
TALIANE SUERDA DE MORA SILVA VIA AUTOMAÇAO + 46,00
JOSEFA JEOVANIA TEIXEIRA DE OLIVEIRA DIAS VIA AUTOMAÇAO + 10,00
SAMUEL SOUZA VIA AUTOMAÇAO + 21,00
MAGNOLIA FAGUNDES ALVES BARBOSA VIA AUTOMAÇAO + 28,00
PAULO RANGEL VIA AUTOMAÇAO + 51,00
ALESSANDRA BELLAGUARDA VIA AUTOMAÇAO + 76,00
ANDRÉA KALINE COSTA DA SILVA VIA AUTOMAÇAO + 10,00
KELLYANE CRISTINE PRATA DE LUCENA RIBEIRO VIA AUTOMAÇAO + 9,00
TASSIA LOURENA DE OLIVEIRA ARAUJO DANTAS VIA AUTOMAÇAO + 4,00
AMANDA DANTAS CADÓ VIA AUTOMAÇAO + 11,00
MARIA ISABEL RAMALHO GONCALVES VIA AUTOMAÇAO + 23,00
ANDREZA CABRAL CÂMARA NUNES VIA AUTOMAÇAO + 25,00
DIÓGENES PEREIRA DA SILVA VIA AUTOMAÇAO + 28,00
ANA RAPHAELLA BARROCA FRANCO VIA AUTOMAÇAO + 14,00
GLADYS NUNES VIEIRA VIA AUTOMAÇAO + 13,00
ANA CYNTHIA PRAXEDES DE AMORIM E SILVA ALMEIDA VIA AUTOMAÇAO + 4,00
ELAINNE VANESSA DE ANDRADE CLEMENTINO VIA AUTOMAÇAO + 20,00
FELIPE LANDEIRA VIA AUTOMAÇAO + 13,00
ANA SANTANA DE ARAÚJO VIA AUTOMAÇAO + 17,00
JULIETE SANTOS VIA AUTOMAÇAO + 16,00
DANIELLY CRISTINA BEZERRA DE SOUZA ALMEIDA VIA AUTOMAÇAO + 99,00
MARIA IVANILDA BERNADINO DA SILVA SEGUNDO VIA AUTOMAÇAO + 40,00
DANIELE DUARTE MENDONÇA BARBOSA VIA AUTOMAÇAO + 33,00
FRANCIDALVA PEDRO DOS SANTOS VIA AUTOMAÇAO + 37,00
LUCAS GABRIEL NUNES DOS SANTOS SÉTIMO B VIA AUTOMAÇAO + 18,00
KRYSSIA ALEIXO DE SOUZA CAROLINO DE MELO VIA AUTOMAÇAO + 71,00
MIKAELY LISIANE DIAS DE AQUINO OLIVEIRA VIA AUTOMAÇAO + 37,00
FERNANDA EDIKA DE SOUZA LOPES VIA AUTOMAÇAO + 41,00
EDUARDO LIMA DE SANTANA VIA AUTOMAÇAO + 40,00
ANDRE MARCOS DA CUNHA VARELA VIA AUTOMAÇAO + 38,00
REBECA DA ROCHA MARQUES LOPES VIA AUTOMAÇAO + 30,00
FLAVIA SILVA DE MACEDO VIA AUTOMAÇAO + 5,00
NILMA CRISTINA VIA AUTOMAÇAO + 122,00
ISABELLY THUANY DE FREITAS CARVALHO VIA AUTOMAÇAO + 34,00
LAYANE ORRICO VIA AUTOMAÇAO + 11,00
MARIA SELMA INACIO DE OLIVEIRA VIA AUTOMAÇAO + 32,00
BETANIA SILVA DE ARAUJO MEDEIROS VIA AUTOMAÇAO + 45,00
LICIA DE CASTRO REGO VIA AUTOMAÇAO + 42,00
ERIKA HERONILDES COSTA DA SILVA VIA AUTOMAÇAO + 28,00
MACLI IRVING DA SILVA VIA AUTOMAÇAO + 72,00
NAIRA CAROLINE DE OLIVEIRA BRITO VIA AUTOMAÇAO + 37,00
ELIANA CARLA GOMES DE ALBUQUERQUE MONTEIRO VIA AUTOMAÇAO + 11,00
SARAH SASKYA SERAFIM DE ARAÚJO VIA AUTOMAÇAO + 18,00
ANDREZA KARINA ALVES PAIVA DUARTE VIA AUTOMAÇAO + 11,00
KALINE RODRIGUES DE FREITAS PAIVA VIA AUTOMAÇAO + 6,00
FERNANDA THEMES SILVA NASCIMENTO FERNANDES VIA AUTOMAÇAO + 24,00
EMILVA DANTAS DA SILVA MENDONÇA VIA AUTOMAÇAO + 23,00
ROBERTO ALVES DA SILVA VIA AUTOMAÇAO + 11,00
EDIONE MENDONÇA MACARIO VIA AUTOMAÇAO + 73,00
MARIA EDUARDA DANTAS TAVARES DA SILVA VIA AUTOMAÇAO + 42,00
SARA RUANA VIA AUTOMAÇAO + 41,00
NATHALLYA KARELLYNE INACIO DUARTE DE MELO OLIVEIRA VIA AUTOMAÇAO + 33,00
MARIA MICARLA DE FREITAS VIA AUTOMAÇAO + 45,00
VIVIANE ARNAUD LOPES DIAS VIA AUTOMAÇAO + 34,00
JOELMA MATIAS VIA AUTOMAÇAO + 29,00
ERIKA PRISCILLA VIA AUTOMAÇAO + 129,00
LÚCIO CARLOS DE OLIVEIRA BARBOSA VIA AUTOMAÇAO + 96,00
LIGIA ANDERSON DA SILVA COSTA ARAUJO VIA AUTOMAÇAO + 33,00
NEUSSANA KELLEN DE ARAUJO MEDEIROS TORREÃO VIA AUTOMAÇAO + 24,00
ANA CAROLINA MAIA DE SÁ VIA AUTOMAÇAO + 33,00
TATIANA DE CARVALHO MACHADO VIA AUTOMAÇAO + 33,00
TALITTA SANTOS NEVES VIA AUTOMAÇAO + 39,00
AGOSTINHO JUSTINO DE ANDRADE NETO VIA AUTOMAÇAO + 18,00
GÊUZILENE EMANUEL LE CRUZ DE FRANÇA DAS CHAGAS VIA AUTOMAÇAO + 20,00
DANIELE ROSEGLEI DA SILVA VIA AUTOMAÇAO + 16,00
ANDREZZA SIMOES DA SILVA VIA AUTOMAÇAO + 29,00
JULIENE ANGELICA RODRIGUES MASCARENHAS MOURA VIA AUTOMAÇAO + 35,00
JAQUELINE WANDERLEI VIA AUTOMAÇAO + 31,00
CIBELE DE CASTRO REGO HERONILDES VIA AUTOMAÇAO + 39,00
O'HARA DANIELE SOARES COUTINHO VIA AUTOMAÇAO + 9,00
KAYNIELLE VANELE VIA AUTOMAÇAO + 23,00
ANA PAULA VIA AUTOMAÇAO + 36,00
MISSERINE DEL VALLE CARVAJAL VICUNA VIA AUTOMAÇAO + 76,00
CHARLENE GABRIEL SOARES DE MELO VIA AUTOMAÇAO + 78,00
RODRIGO REGLY CARVALHO VIA AUTOMAÇAO + 47,00
MARUSK MIKAELLY ALVES DE LIMA VIA AUTOMAÇAO + 29,00
JANE KELLY DOS SANTOS CANINDE GOMES VIA AUTOMAÇAO + 32,00
ELIONORA BATISTA DOS SANTOS VIA AUTOMAÇAO + 61,00
JACQUELINE EVANGELISTA DE SOUSA VIA AUTOMAÇAO + 109,00
ANA CAROLINA NOVAES FERNANDES VIA AUTOMAÇAO + 99,00
JACIANE FERREIRA DE LIMA VIDAL VIA AUTOMAÇAO + 41,00
BETANIA CARDOSO VIA AUTOMAÇAO + 71,00
LIDNADJA CRISTINA SILVEIRA DE SOUZA VIA AUTOMAÇAO + 20,00
DAYSE SOARES DOS SANTOS VIA AUTOMAÇAO + 34,00
THIAGO MARTINS DE SOUZA VIA AUTOMAÇAO + 26,00
MARCUS VINICIUS DOS SANTOS COSTA AQUINO VIA AUTOMAÇAO + 12,00
KATIA PATRICIA DE OLIVEIRA AQUINO VIA AUTOMAÇAO + 40,00
GABRIELA ARAUJO SARAIVA NERY VIA AUTOMAÇAO + 24,00
YANNE BARRETO VIA AUTOMAÇAO + 119,00
LIDIANE DE LIMA SILVA VIDIGAL + 10,00
    """
    
    # Extrair nomes do relatório Infinite Pay
    print("📊 Extraindo nomes do relatório Infinite Pay...")
    nomes_infinitepay = extrair_nomes_infinitepay(relatorio_infinitepay)
    print(f"✅ {len(nomes_infinitepay)} nomes extraídos do relatório")
    
    # Ler nomes do CSV
    print(f"📋 Lendo nomes do CSV: {csv_file}")
    nomes_csv = set()
    try:
        with open(csv_file, 'r', encoding='utf-8') as arquivo:
            leitor = csv.DictReader(arquivo)
            for linha in leitor:
                nome = linha['Nome'].strip()
                if nome:
                    nomes_csv.add(nome)
        print(f"✅ {len(nomes_csv)} nomes lidos do CSV")
    except FileNotFoundError:
        print(f"❌ Arquivo {csv_file} não encontrado!")
        return
    except Exception as e:
        print(f"❌ Erro ao ler CSV: {str(e)}")
        return
    
    # Normalizar nomes para comparação
    nomes_infinitepay_norm = {normalizar_nome(nome) for nome in nomes_infinitepay}
    nomes_csv_norm = {normalizar_nome(nome) for nome in nomes_csv}
    
    # Encontrar nomes que estão no CSV mas não no relatório
    nomes_faltando = nomes_csv_norm - nomes_infinitepay_norm
    
    print(f"\n🔍 RESULTADO DA COMPARAÇÃO:")
    print(f"📊 Total no CSV: {len(nomes_csv)}")
    print(f"📊 Total no relatório: {len(nomes_infinitepay)}")
    print(f"❌ Faltando no relatório: {len(nomes_faltando)}")
    
    if nomes_faltando:
        print(f"\n📋 RESPONSÁVEIS QUE ESTÃO NO CSV MAS NÃO NO RELATÓRIO:")
        print("=" * 80)
        
        # Converter nomes normalizados de volta para nomes originais
        nomes_faltando_originais = []
        for nome_norm in nomes_faltando:
            for nome_original in nomes_csv:
                if normalizar_nome(nome_original) == nome_norm:
                    nomes_faltando_originais.append(nome_original)
                    break
        
        # Ordenar alfabeticamente
        nomes_faltando_originais.sort()
        
        for i, nome in enumerate(nomes_faltando_originais, 1):
            print(f"{i:2d}. {nome}")
        
        # Salvar em arquivo
        arquivo_saida = "responsaveis_faltando_31agosto.csv"
        with open(arquivo_saida, 'w', newline='', encoding='utf-8') as arquivo:
            writer = csv.writer(arquivo)
            writer.writerow(['Nome'])
            for nome in nomes_faltando_originais:
                writer.writerow([nome])
        
        print(f"\n💾 Lista salva em: {arquivo_saida}")
        
    else:
        print("\n✅ Todos os responsáveis do CSV estão no relatório!")
    
    print("\n" + "=" * 60)

if __name__ == "__main__":
    main() 